# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.nextest]
command = [
    "cargo", "nextest", "run",
    "--hide-progress-bar", "--failure-output", "final"
]
need_stdout = true
analyzer = "nextest"

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--no-deps", "--open"]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change

[jobs.run-frontend]
command = [
    "cargo", "run", "-p", "frontend",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-backend]
command = [
    "cargo", "run", "-p", "backend",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[keybindings]
c = "job:clippy"
shift-f = "job:run-frontend"
shift-b = "job:run-backend"
